<div class="col-md-3">
               <h3 class="text-center" style="line-height: 16px; padding-top: 16px; margin-top: 0px; margin-bottom: 20px;" id="napsali-o-ns">Napsali o nás</h3>
                  
                  
                      
                      
                          
                                <strong>14.3.2017</strong> <strong><a href="http://www.mmdecin.cz/obcan/zpravodajstvi/zpravy-z-radnice/item/1967-zapojte-se-do-celorepublikove-akce-uklidme-cesko" target="_blank">Zapojte se do celorepublikové akce</a></strong><br><em>web: mmdecin.cz</em><br>
                          
                      
                  
                      
                      
                          
                                <strong>14.3.2017</strong> <strong><a href="http://moderniobec.cz/uz-za-mesic-propukne-velky-uklid-ceska-pridejte-se-take/" target="_blank">Známe vítěze soutěže DOODPADU. Přehrajte si spolu s námi videoklip, s nímž triumfoval v republikovém finále!</a></strong><br><em>web: moderniobec.cz</em><br>
                          
                      
                  
                      
                      
                          
                                <strong>9.3.2017</strong> <strong><a href="http://www.enviweb.cz/rss/zemedelstvi/139572/presne-za-mesic-se-chysta-velky-uklid-ceska-pridejte-se-take?utm_source=rss&utm_medium=rss&utm_campaign=rss_clankyall" target="_blank">Přesně za měsíc se chystá velký úklid Česka, přidejte se také!</a></strong><br><em>web: enviweb.cz</em><br>
                          
                      
                  
                      
                      
                          
                                <strong>9.3.2017</strong> <strong><a href="http://www.vodainfo.cz/do-uklidu-zbyva-mesic-a-je-nas-tisic/" target="_blank">Do úklidu zbývá měsíc a je nás tisíc!</a></strong><br><em>web: vodainfo.cz</em><br>
                          
                      
                  
                      
                      
                          
                                <strong>9.3.2017</strong> <strong><a href="http://www.nazeleno.cz/aktualne/za-mesic-se-bude-uklizet-cesko-pridejte-se.aspx" target="_blank">Aktuálně: Za měsíc se bude uklízet Česko. Přidejte se</a></strong><br><em>web: nazeleno.cz</em><br>
                          
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  

                <a href="/about/vMediich"><button type="button" class="btn btn-default btn-xs pull-right" style="margin-right: 25px; margin-top: 12px;">
                   další články <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </button></a>
                <span style="display: none;"><a href="http://www.seonastroje.cz/">SEO</a> webu sledují <a href="http://www.seonastroje.cz/">SEO nástroje</a>.cz</span>
            </div>
        
