<div class="col-md-3 noline" style="padding-bottom: 0px; margin-bottom: 0px;">
                <h3 class="text-center" style="line-height: 16px; padding-top: 16px; margin-top: 0px; margin-bottom: 20px;" id="co-je-u-ns-novho">Co je u nás nového</h3>


                
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                     
                    
                    
                     
                    
                    
                    
                     
                
                 
                        <strong>4.3.2017</strong> <strong><a href="/news/58b9516e291844696f8b4572">Trika budou :-)</a></strong><br>
                 
                        <strong>3.3.2017</strong> <strong><a href="/news/58b94fd3291844696f8b4570">Již je možno žádat o materiál!</a></strong><br>
                 
                        <strong>28.2.2017</strong> <strong><a href="/news/58b5f80d29184434518b45c1">Staňme se změnou!</a></strong><br>
                 
                        <strong>21.2.2017</strong> <strong><a href="/news/58ab6136291844d0348b4567">„Musíme to uklidit!“ zní od ochránců přírody</a></strong><br>
                 
                        <strong>8.2.2017</strong> <strong><a href="/news/5899e9e6291844c1298b456b">Již za 2 měsíce proběhne velký jarní úklid. Přidejte se!</a></strong><br>
                 
                        <strong>8.1.2017</strong> <strong><a href="/news/587dfb892918447d128b4567">Ukliďme svět, ukliďme Česko letos s významnou podporou MŽP</a></strong><br>
                 
                        <strong>8.12.2016</strong> <strong><a href="/news/5849225b291844e87e8b456b">Symbolické zakončení sezóny</a></strong><br>
                 
                        <strong>29.11.2016</strong> <strong><a href="/news/583d4ee8291844cd488b4570">Poslední letošní úklid</a></strong><br>
                 
                <a href="/news/"><button type="button" class="btn btn-default btn-xs pull-right" style="margin-right: 25px; margin-top: 12px;">
                   další aktuality <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </button></a>
            </div>
            
