<div class="col-md-3">
               <h3 class="text-center" style="line-height: 16px; padding-top: 16px; margin-top: 0px; margin-bottom: 20px;" id="napsali-o-ns">Napsali o nás</h3>
                  
                  
                      
                      
                          
                                <strong>28.2.2017</strong> <strong>
                                Ústí chystá velký jarní úklid</strong><br><em>tisk: Ústecký deník (str. 2)</em><br>
                          
                      
                  
                      
                      
                          
                                <strong>27.2.2017</strong> <strong><a href="http://breclavsky.denik.cz/z-regionu/cerne-skladky-pomahaji-kamery-i-fotopasti-20170227.html" target="_blank">Černé skládky? Pomáhají kamery i fotopasti</a></strong><br><em>web: breclavsky.denik.cz</em><br>
                          
                      
                  
                      
                      
                          
                                <strong>27.2.2017</strong> <strong><a href="http://www.bydlet.cz/418077-ekologie-kolem-nas-sklenik-make-up-i-elektrokolobezka/" target="_blank">Ekologie kolem nás: skleník, make-up i elektrokoloběžka</a></strong><br><em>web: bydlet.cz</em><br>
                          
                      
                  
                      
                      
                          
                                <strong>27.2.2017</strong> <strong>
                                Černé skládky: pomáhají kamery nebo fotopasti</strong><br><em>tisk: Deník (Jihomoravský kraj 6 mutací) (str. 3)</em><br>
                          
                      
                  
                      
                      
                          
                                <strong>27.2.2017</strong> <strong><a href="http://ekolist.cz/cz/zpravodajstvi/zpravy/musime-to-uklidit-zni-od-ochrancu" target="_blank">"Musíme to uklidit!" zní od ochránců</a></strong><br><em>web: ekolist.cz</em><br>
                          
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  
                      
                      
                  

                <a href="/about/vMediich"><button type="button" class="btn btn-default btn-xs pull-right" style="margin-right: 25px; margin-top: 12px;">
                   další články <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </button></a>
                <span style="display: none;"><a href="http://www.seonastroje.cz/">SEO</a> webu sledují <a href="http://www.seonastroje.cz/">SEO nástroje</a>.cz</span>
            </div>
        
